name: Release and Publish to NPM

on:
  push:
    branches:
      - main # 或者你的主分支名称
    paths:
      - ".changeset/*.md" # 仅在 .changeset 文件夹中的 .md 文件发生变更时触发
  #      - "package.json" # 如果 package.json 发生变更也触发
  workflow_dispatch: # 允许手动触发工作流

#on:
#  push:
#    tags:
#      - "v*" # 匹配以 v 开头的标签（如 v1.0.0）
#  workflow_dispatch:


permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 24 ]

    steps:
      # 1. 检出代码
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Update npm for Trusted Publishing
        run: npm install -g npm@11.6.2

      - name: Install Dependencies
        run: pnpm install --strict-peer-dependencies

      # 5. 使用 Changesets Action 自动化发布
      - name: Create Release PR or publish stable version to npm
        id: changesets
        uses: changesets/action@v1
        with:
          createGithubReleases: true # 启用自动创建 GitHub Release
          publish: pnpm changeset publish
          version: pnpm changeset version
          title: ${{ github.ref_name == 'main' && 'Publish a new stable version' || 'Publish a new pre-release version' }}
          commit: >-
            ${{ github.ref_name == 'main' && 'chore(release): publish a new release version' || 'chore(release): publish a new pre-release version' }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#          NPM_CONFIG_PROVENANCE: true # 启用 NPM Provenance 功能
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_ACCESS: public

      # 6. 打印日志以确认版本号
      - name: Print Version and Published Package
        if: success() # 仅在上一步成功时执行
        run: |
          echo "Current package.json version: $(node -p "require('./package.json').version")"
          echo "Latest version on NPM: $(npm show @tinyflow-ai/react version)"
